export {
  splitReveal,
  magnetic,
  marquee,
  flipList,
  parallax,
  scrambleText,
  magneticCursor,
  tilt,
  spotlight,
  scrollProgress,
  stagger,
  gradientText,
  ripple,
  blur,
  pin,
} from './actions';
export type { FlipListActionParams } from './actions';

export type {
  MotionInstance,
  Target,
  SplitRevealOptions,
  SplitRevealType,
  MagneticOptions,
  MarqueeOptions,
  MarqueeDirection,
  FlipListOptions,
  FlipListInstance,
  ParallaxOptions,
  ScrambleTextOptions,
  MagneticCursorOptions,
  TiltOptions,
  SpotlightOptions,
  ScrollProgressOptions,
  StaggerOptions,
  GradientTextOptions,
  RippleOptions,
  BlurOptions,
  PinOptions,
} from '@bwo-ui/core';
